language: node_js
node_js:
  - "4"

before_install:
  - npm install bower -g
  - npm install grunt-cli -g
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
  
script:
  - grunt karma:singleRun
  - grunt protractor
 
after_success: 'npm run coveralls'

branches:
  only:
    - master
  
cache:
  directories:
  - app/bower_components
  - node_modules

notifications:
  email: true